### PR TITLE
Imported upstream v2.5.0.176

### PR DESCRIPTION
**Pull request by severin-lemaignan**

### CODE REVIEW

**Comment by vrabaud** [comment]
That's a proper bloom release ? Feel free to merge, and release. The patch was there to remove some debug library.

**Comment by severin-lemaignan** [comment]
Well, before releasing, we should agree on switching to `libqi-2.5` :-) I've no clue what kind of incompatibilities this may introduce with Nao in the field (even though it works fine here to interact from the desktop with a nao running naoqi 2.1.2.17)

**Comment by vrabaud** [comment]
you can still revert :)
Any particular reason to switch to 2.5 ? (if it's released, go for it !)
@Klaim, @alkino, feel free to advise. Thx.

**Comment by suryaambrose** [comment]
I think libqi 2.5 is not officially released yet (naoqi 2.5 is not)

**Comment by vrabaud** [comment]
well, it has been tagged sooooo, I guess it's released ?

**Comment by alkino** [comment]
No it's not. libqi 2.5.0.176 is released but is not a part of naoqi 2.5.
It's why it has a long name and not a short one.

2016-03-13 8:38 GMT+01:00 Vincent Rabaud notifications@github.com:

> well, it has been tagged sooooo, I guess it's released ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-naoqi/libqi-release/pull/1#issuecomment-195908466
> .

## 

*This email and any attachment thereto are confidential and intended solely 
for the use of the individual or entity to whom they are addressed.If you 
are not the intended recipient, please be advised that disclosing, copying, 
distributing or taking any action in reliance on the contents of this email 
is strictly prohibited. In such case, please immediately advise the sender, 
and delete all copies and attachment from your system.This email shall not 
be construed and is not tantamount to an offer, an acceptance of offer, or 
an agreement by Aldebaran Robotics on any discussion or contractual 
document whatsoever. No employee or agent is authorized to represent or 
bind Aldebaran Robotics to third parties by email, or act on behalf of 
Aldebaran Robotics by email, without express written confirmation by 

## Aldebaran Robotics’ duly authorized representatives.*

_Ce message électronique et éventuelles pièces jointes sont confidentiels, 
et exclusivement destinés à la personne ou l'entité à qui ils sont 
adressés._

_Si vous n'êtes pas le destinataire visé, vous êtes prié de ne pas 
divulguer, copier, distribuer ou prendre toute décision sur la foi de ce 
message électronique. Merci d'en aviser immédiatement l'expéditeur et de 
supprimer toutes les copies et éventuelles pièces jointes de votre système._

_Ce message électronique n'équivaut pas à une offre, à une acceptation 
d’offre, ou à un accord d'Aldebaran Robotics sur toute discussion ou 
document contractuel quel qu’il soit, et ne peut être interprété comme tel. 
Aucun employé ou agent d’Aldebaran Robotics n'est autorisé à représenter ou 
à engager la société par email, ou à agir au nom et pour le compte de la 
société par email, sans qu’une confirmation écrite soit donnée par le 
représentant légal d’Aldebaran Robotics ou par toute autre personne ayant 
reçu délégation de pouvoir appropriée._

**Comment by vrabaud** [comment]
right, that's what I meant by "it". libqi is released so let's use it. @severin-lemaignan , did you do a proper bloom release ?

**Comment by severin-lemaignan** [comment]
Not yet (was away for a conference over the last 15 days). I'll have a look in a week or so (if you want to go ahead in the meantime, please do!)

**Comment by vrabaud** [comment]
Properly released with bloom.

**Pull request closed without merging**
