### PR TITLE
nao_libqi 2.5.0.176

### PR DESCRIPTION
**Pull request by severin-lemaignan**
Compilation tested on Ubuntu 15.10 with ROS Jade

### CODE REVIEW

**Comment by severin-lemaignan** [comment]
(guys, I don't know what is your current schedule for importing more recent versions of libqi, and feel free to ignore/close the PR if things are already organized in a different way! -- I only did it because I wasn't able to compile the ROS Jade `naoqi_libqi` package on Ubuntu 15.10 due to Boost incompatibilities)

**Comment by vrabaud** [comment]
hmmm, this is a release repo, you need to apply patches with bloom. It should be trivial if you follow: http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty#Future_Releases
Good job for you @suryaambrose  :)

**Comment by vrabaud** [comment]
Properly updated with bloom.

**Comment by vrabaud** [comment]
@suryaambrose , that new release harmlessly breaks naoqi_driver, please fix and release: http://build.ros.org/job/Ibin_uS64__naoqi_driver__ubuntu_saucy_amd64__binary/8/console

**Comment by suryaambrose** [comment]
Well I can't ! 
I fixed the compilation issues, but I now have a linkage issue due to ... boost incompatibilities :p. 

Is it possible to have libqi-2.3 for indigo and previous, and 2.5 for jade and futures ? Because I guess my problem comes from the fact that I use Ubuntu 14.04 and therefore have boost 1.54. 
I think I can handle this, I just need your go !

**Comment by vrabaud** [comment]
Ubuntu 14.04 is supported by Indigo and Jade so we cannot do that. Any help you could get from @Klaim, @alkino ? BTW, where are the install instructions and dependency requirements for libqi, I cannot find them in the README and http://doc.aldebaran.com/libqi/ . Thx

**Comment by suryaambrose** [comment]
Here I guess : https://github.com/aldebaran/libqi/blob/master/qiproject.xml
But the required versions are not specified.

**Comment by suryaambrose** [comment]
@severin-lemaignan which version of boost do you have. It seems libqi 2.5.0.176 uses the same version of boost as 2.3 (1.55). Which version is native in Ubuntu 15.10 ?

**Comment by vrabaud** [comment]
1.58 http://packages.ubuntu.com/wily/libboost-all-dev

**Comment by Klaim** [comment]
@vrabaud Could you create a ticket about what info you think is missing in the readme? I have plans to update it but couldn't do it yet.

Anyway, 2.5 version will not support ubuntu 15.10 officially because 15.10 gcc have runtime bugs (I don't know if they have been fixed yet) related to exception handling. Also, current master is targetting boost 1.59.

**Comment by vrabaud** [comment]
done in https://github.com/aldebaran/libqi/issues/13

**Pull request closed without merging**
